/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Set Signup */
        put: operations["v1_set_signup_api_v1_admin_signup_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Users */
        get: operations["v1_users_api_v1_admin_users_get"];
        put?: never;
        /** V1 Create User */
        post: operations["v1_create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** V1 Delete User */
        delete: operations["v1_delete_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Toggle Active */
        put: operations["v1_toggle_active_api_v1_admin_users__user_id__active_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Reset Password */
        put: operations["v1_reset_password_api_v1_admin_users__user_id__password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/reassign-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V1 Reassign Cases
         * @description Move every case owned by ``user_id`` to ``new_owner_id`` (unblocks delete).
         */
        post: operations["v1_reassign_cases_api_v1_admin_users__user_id__reassign_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Set User Role */
        put: operations["v1_set_user_role_api_v1_admin_users__user_id__role_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Auth Config */
        get: operations["v1_auth_config_api_v1_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** V1 Login */
        post: operations["v1_login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** V1 Logout */
        post: operations["v1_logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** V1 Signup */
        post: operations["v1_signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Cases Directory */
        get: operations["v1_cases_directory_api_v1_cases_get"];
        put?: never;
        /**
         * V1 Create Case
         * @description Create a case and its initial active proceeding.
         */
        post: operations["v1_create_case_api_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/confirm-close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V1 Confirm Close
         * @description Accept an AI close suggestion: close the case and all its proceedings.
         */
        post: operations["v1_confirm_close_api_v1_cases__case_id__confirm_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/dismiss-close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V1 Dismiss Close
         * @description Reject an AI close suggestion: clear the flag, keep the status.
         */
        post: operations["v1_dismiss_close_api_v1_cases__case_id__dismiss_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Home */
        get: operations["v1_home_api_v1_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home/review-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V1 Review All
         * @description Mark everything new as reviewed: advances last_home_visit to now.
         */
        post: operations["v1_review_all_api_v1_home_review_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Search */
        get: operations["v1_search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Account */
        get: operations["v1_account_api_v1_settings_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/account/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Change Email */
        put: operations["v1_change_email_api_v1_settings_account_email_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Change Password */
        put: operations["v1_change_password_api_v1_settings_account_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/account/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Update Profile */
        put: operations["v1_update_profile_api_v1_settings_account_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * V1 Ai Settings
         * @description Configuration only — no network probes (see /health and /models).
         */
        get: operations["v1_ai_settings_api_v1_settings_ai_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/debug-redact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Debug Redact */
        put: operations["v1_debug_redact_api_v1_settings_ai_debug_redact_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/extraction-engine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Set Engine */
        put: operations["v1_set_engine_api_v1_settings_ai_extraction_engine_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Role Health */
        get: operations["v1_role_health_api_v1_settings_ai_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** V1 Create Instance */
        post: operations["v1_create_instance_api_v1_settings_ai_instances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/instances/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Update Instance */
        put: operations["v1_update_instance_api_v1_settings_ai_instances__instance_id__put"];
        post?: never;
        /** V1 Remove Instance */
        delete: operations["v1_remove_instance_api_v1_settings_ai_instances__instance_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/instances/{instance_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Instance Models */
        get: operations["v1_instance_models_api_v1_settings_ai_instances__instance_id__models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/instances/{instance_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** V1 Test Instance */
        post: operations["v1_test_instance_api_v1_settings_ai_instances__instance_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/ocr-concurrency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Ocr Concurrency */
        put: operations["v1_ocr_concurrency_api_v1_settings_ai_ocr_concurrency_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/rebuild-index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V1 Rebuild Index
         * @description Resize both pgvector columns to the configured dimension, then re-embed.
         */
        post: operations["v1_rebuild_index_api_v1_settings_ai_rebuild_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V1 Reindex
         * @description Re-embed every document with the current settings (no column change).
         */
        post: operations["v1_reindex_api_v1_settings_ai_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/reindex/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Reindex Status */
        get: operations["v1_reindex_status_api_v1_settings_ai_reindex_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * V1 Set Role
         * @description Point a role at an endpoint and, if ``model`` is set, pick its model.
         */
        put: operations["v1_set_role_api_v1_settings_ai_roles__role__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ai/worker-concurrency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Worker Concurrency */
        put: operations["v1_worker_concurrency_api_v1_settings_ai_worker_concurrency_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/appearance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Appearance */
        get: operations["v1_appearance_api_v1_settings_appearance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/appearance/dashboard-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Save Dashboard Cards */
        put: operations["v1_save_dashboard_cards_api_v1_settings_appearance_dashboard_cards_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/appearance/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Save Theme */
        put: operations["v1_save_theme_api_v1_settings_appearance_theme_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/appearance/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * V1 Save Timezone
         * @description The display timezone is global (one workspace), so admins only.
         */
        put: operations["v1_save_timezone_api_v1_settings_appearance_timezone_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Data */
        get: operations["v1_data_api_v1_settings_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/data/clear-all-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** V1 Clear All Data */
        post: operations["v1_clear_all_data_api_v1_settings_data_clear_all_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/data/debug-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Debug Logs */
        get: operations["v1_debug_logs_api_v1_settings_data_debug_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/data/debug-logs/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Debug Log */
        get: operations["v1_debug_log_api_v1_settings_data_debug_logs_view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/data/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * V1 Export
         * @description Download the whole workspace as a zip (GDPR Art. 15/20).
         */
        get: operations["v1_export_api_v1_settings_data_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/data/reset-enrichment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** V1 Reset Enrichment */
        post: operations["v1_reset_enrichment_api_v1_settings_data_reset_enrichment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/gmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Gmail */
        get: operations["v1_gmail_api_v1_settings_gmail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/gmail/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * V1 Backfill
         * @description Queue a one-off import of the last ``days`` days of the user's mailbox.
         */
        post: operations["v1_backfill_api_v1_settings_gmail_backfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/gmail/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** V1 Save Filters */
        put: operations["v1_save_filters_api_v1_settings_gmail_filters_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Identity */
        get: operations["v1_identity_api_v1_settings_identity_get"];
        /** V1 Save Identity */
        put: operations["v1_save_identity_api_v1_settings_identity_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Shell */
        get: operations["v1_shell_api_v1_shell_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V1 Worker Queue */
        get: operations["v1_worker_queue_api_v1_worker_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/worker-queue/retry-failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** V1 Retry Failed */
        post: operations["v1_retry_failed_api_v1_worker_queue_retry_failed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountView */
        AccountView: {
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string;
            /** Has Password */
            has_password: boolean;
            role: components["schemas"]["UserRole"];
        };
        /**
         * ActionItemType
         * @description Type of action derived from a document.
         * @enum {string}
         */
        ActionItemType: "deadline" | "court_date" | "response_required" | "filing_required" | "payment_due";
        /** AdminPasswordReset */
        AdminPasswordReset: {
            /** New Password */
            new_password: string;
        };
        /** AdminReassignCases */
        AdminReassignCases: {
            /** New Owner Id */
            new_owner_id: number;
        };
        /** AdminRoleUpdate */
        AdminRoleUpdate: {
            role: components["schemas"]["UserRole"];
        };
        /** AdminUser */
        AdminUser: {
            /** Created At */
            created_at: string | null;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /** Owned Case Count */
            owned_case_count: number;
            role: components["schemas"]["UserRole"];
        };
        /** AdminUserCreate */
        AdminUserCreate: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** @default user */
            role: components["schemas"]["UserRole"];
        };
        /** AdminUsersView */
        AdminUsersView: {
            /** Signup Enabled */
            signup_enabled: boolean;
            /** Users */
            users: components["schemas"]["AdminUser"][];
        };
        /** AiHealth */
        AiHealth: {
            /** Detail */
            detail: string;
            /** Ok */
            ok: boolean;
            /** Provider */
            provider?: string | null;
        };
        /** AiInstance */
        AiInstance: {
            /** Base Url */
            base_url: string;
            /** Embed Dim */
            embed_dim: number | null;
            /** Embed Model */
            embed_model: string;
            /** Has Api Key */
            has_api_key: boolean;
            /** Id */
            id: string;
            /** Is External */
            is_external: boolean;
            /** Label */
            label: string;
            /** Ocr Model */
            ocr_model: string;
            /** Summary Model */
            summary_model: string;
        };
        /** AiInstanceInput */
        AiInstanceInput: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url: string;
            /** Label */
            label: string;
        };
        /** AiRole */
        AiRole: {
            /** Active Id */
            active_id: string | null;
            /** Embed Dim */
            embed_dim: number | null;
            /** Hint */
            hint: string;
            /** Label */
            label: string;
            /** Model */
            model: string;
            /**
             * Role
             * @enum {string}
             */
            role: "chat" | "embed" | "ocr";
        };
        /** AiSettingsView */
        AiSettingsView: {
            embed_index: components["schemas"]["EmbedIndex"];
            /**
             * Extraction Engine
             * @enum {string}
             */
            extraction_engine: "chandra" | "docling";
            /** Instances */
            instances: components["schemas"]["AiInstance"][];
            /** Ocr Concurrency */
            ocr_concurrency: number;
            reindex_job: components["schemas"]["ReindexJob"] | null;
            /** Roles */
            roles: components["schemas"]["AiRole"][];
            /** Worker Concurrency */
            worker_concurrency: number;
        };
        /** AppearanceView */
        AppearanceView: {
            dashboard_cards: components["schemas"]["DashboardCards"];
            /**
             * Theme
             * @enum {string}
             */
            theme: "dark" | "light";
            /** Timezone */
            timezone: string;
            /** Timezone Choices */
            timezone_choices: string[];
        };
        /**
         * AuthConfig
         * @description What the public sign-in screens need to know before anyone is logged in.
         */
        AuthConfig: {
            /** First Run */
            first_run: boolean;
            /** Oidc Enabled */
            oidc_enabled: boolean;
            /** Oidc Provider Name */
            oidc_provider_name: string;
            /** Signup Enabled */
            signup_enabled: boolean;
        };
        /**
         * CaseCard
         * @description One case as shown on Home and in the Cases directory.
         */
        CaseCard: {
            /** Client Name */
            client_name: string;
            /** Days Since Activity */
            days_since_activity: number;
            /** Doc Count */
            doc_count: number;
            /** Exposure Eur */
            exposure_eur: number;
            /** Id */
            id: string;
            /** Is Dormant */
            is_dormant: boolean;
            /** Is Draft */
            is_draft: boolean;
            /** Last Activity At */
            last_activity_at: string | null;
            /** Matter Type */
            matter_type: string;
            max_significance: components["schemas"]["SignificanceTier"] | null;
            /** New Docs */
            new_docs: number;
            next_action: components["schemas"]["NextAction"] | null;
            /** Open Action Count */
            open_action_count: number;
            /** Opposing Party */
            opposing_party: string;
            /** Pending Close */
            pending_close: boolean;
            /** Proceeding Name */
            proceeding_name: string;
            status: components["schemas"]["CaseStatus"];
            /** Status Label */
            status_label: string;
            /** Title */
            title: string;
        };
        /** CaseCreate */
        CaseCreate: {
            /** Case Id */
            case_id: string;
            /** Court Name */
            court_name: string;
            /** @default de */
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** Title */
            title: string;
        };
        /** CaseCreated */
        CaseCreated: {
            /** Id */
            id: string;
        };
        /**
         * CaseStatus
         * @enum {string}
         */
        CaseStatus: "intake" | "discovery" | "pre_trial" | "trial" | "post_trial" | "closed";
        /** CasesDirectory */
        CasesDirectory: {
            /** Cases */
            cases: components["schemas"]["CaseCard"][];
            /** Counts By Status */
            counts_by_status: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** ConcurrencyResult */
        ConcurrencyResult: {
            /** Applied Live */
            applied_live: boolean;
            /** Concurrency */
            concurrency: number;
        };
        /** ConcurrencyUpdate */
        ConcurrencyUpdate: {
            /** Concurrency */
            concurrency: number;
        };
        /** CurrentUser */
        CurrentUser: {
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string;
            /** Id */
            id: number;
            role: components["schemas"]["UserRole"];
        };
        /** DashboardCards */
        DashboardCards: {
            /**
             * Action Items
             * @default true
             */
            action_items: boolean;
            /**
             * Costs
             * @default true
             */
            costs: boolean;
            /**
             * Documents
             * @default true
             */
            documents: boolean;
        };
        /** DataView */
        DataView: {
            /** Ai Debug Redact */
            ai_debug_redact: boolean;
            /** Case Count */
            case_count: number;
            /** Claim Count */
            claim_count: number;
            /** Cost Count */
            cost_count: number;
            /** Db Size Mb */
            db_size_mb: number;
            /** Doc Count */
            doc_count: number;
        };
        /** DebugLogList */
        DebugLogList: {
            /** Log Root */
            log_root: string;
            /** Rows */
            rows: components["schemas"]["DebugLogRow"][];
        };
        /** DebugLogRow */
        DebugLogRow: {
            /** Duration Ms */
            duration_ms: number | null;
            /** Kind */
            kind: string | null;
            /** Model */
            model: string | null;
            /** Path */
            path: string | null;
            /** Scope Id */
            scope_id: string | null;
            /** Stage */
            stage: string | null;
            /** Status */
            status: string | null;
            /** Ts */
            ts: string | null;
        };
        /** DebugLogView */
        DebugLogView: {
            /** Body */
            body: string;
            /** Path */
            path: string;
        };
        /** DebugRedactUpdate */
        DebugRedactUpdate: {
            /** Enabled */
            enabled: boolean;
        };
        /** EmailChange */
        EmailChange: {
            /**
             * Current Password
             * @default
             */
            current_password: string;
            /** New Email */
            new_email: string;
        };
        /** EmbedIndex */
        EmbedIndex: {
            /** Dim */
            dim: number;
            /** Index Dim */
            index_dim: number | null;
            /** Mismatch */
            mismatch: boolean;
            /** Model */
            model: string;
        };
        /**
         * ErrorResponse
         * @description Body of every non-2xx ``/api/v1`` response.
         *
         *     ``code`` is a stable machine-readable identifier the client branches on;
         *     ``detail`` is the human-readable message it may show as-is.
         */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
        };
        /** ExtractionEngineUpdate */
        ExtractionEngineUpdate: {
            /**
             * Engine
             * @enum {string}
             */
            engine: "chandra" | "docling";
        };
        /** FailedDoc */
        FailedDoc: {
            /** Batch Id */
            batch_id: number | null;
            /** Doc Id */
            doc_id: number;
            /** Error */
            error: string;
            /** Stage */
            stage: string;
            /** Title */
            title: string;
        };
        /** GmailBackfill */
        GmailBackfill: {
            /**
             * Days
             * @enum {integer}
             */
            days: 90 | 365 | 1825;
        };
        /** GmailFilters */
        GmailFilters: {
            /** Allowlist */
            allowlist: string[];
            /**
             * Label Filter
             * @default
             */
            label_filter: string;
        };
        /** GmailView */
        GmailView: {
            /** Allowlist */
            allowlist: string[];
            /** Connected */
            connected: boolean;
            /** Connected At */
            connected_at: string | null;
            /** Label Filter */
            label_filter: string;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Oauth Start Url */
            oauth_start_url: string;
        };
        /** HomeActionItem */
        HomeActionItem: {
            action_type: components["schemas"]["ActionItemType"];
            /** Case Id */
            case_id: string;
            /** Case Title */
            case_title: string;
            /** Description */
            description: string | null;
            /** Due Date */
            due_date: string | null;
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /** HomeDeltaCase */
        HomeDeltaCase: {
            /** Case Id */
            case_id: string;
            /** Case Title */
            case_title: string;
            /** Doc Titles */
            doc_titles: string[];
            max_significance: components["schemas"]["SignificanceTier"];
            /** New Actions */
            new_actions: number;
            /** New Doc Count */
            new_doc_count: number;
        };
        /** HomeSignal */
        HomeSignal: {
            /** Action */
            action: string;
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Link */
            link: string;
            /** Severity */
            severity: string;
            /** Title */
            title: string;
        };
        /** HomeTriageBundle */
        HomeTriageBundle: {
            /** Case Id */
            case_id: string | null;
            /** Doc Count */
            doc_count: number;
            /** Id */
            id: number;
            pipeline: components["schemas"]["PipelineCounts"];
            /** Received At */
            received_at: string | null;
            /** Sender Email */
            sender_email: string | null;
            status: components["schemas"]["IngestBatchStatus"];
            /** Suggested Case Id */
            suggested_case_id: string | null;
            /** Title */
            title: string;
        };
        /** HomeView */
        HomeView: {
            /** Active Cases */
            active_cases: components["schemas"]["CaseCard"][];
            /** Caught Up */
            caught_up: boolean;
            /** Delta Cases */
            delta_cases: components["schemas"]["HomeDeltaCase"][];
            /** Draft Cases */
            draft_cases: components["schemas"]["CaseCard"][];
            /** Greeting */
            greeting: string;
            /** Last Home Visit */
            last_home_visit: string | null;
            /**
             * Now
             * Format: date-time
             */
            now: string;
            /** Signals */
            signals: components["schemas"]["HomeSignal"][];
            /** Today Items */
            today_items: components["schemas"]["HomeActionItem"][];
            /** Triage Bundles */
            triage_bundles: components["schemas"]["HomeTriageBundle"][];
            /** User Name */
            user_name: string;
        };
        /** IdentityView */
        IdentityView: {
            /** Own Parties */
            own_parties: string[];
            /** Own Self */
            own_self: string;
            /** User Context */
            user_context: string;
        };
        /**
         * IngestBatchStatus
         * @enum {string}
         */
        IngestBatchStatus: "pending" | "processing" | "completed" | "failed" | "dismissed" | "awaiting_slicing";
        /**
         * Jurisdiction
         * @description Case jurisdiction for cost system.
         * @enum {string}
         */
        Jurisdiction: "de" | "uk" | "us" | "other";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /**
             * Next
             * @default /
             */
            next: string;
            /** Password */
            password: string;
        };
        /** MaintenanceResult */
        MaintenanceResult: {
            /** Message */
            message: string;
        };
        /** ModelsView */
        ModelsView: {
            /** Chat */
            chat: string[];
            /** Embed */
            embed: string[];
            /** Ocr */
            ocr: string[];
        };
        /** NextAction */
        NextAction: {
            action_type: components["schemas"]["ActionItemType"];
            /** Due Date */
            due_date: string | null;
            /** Title */
            title: string;
        };
        /** PasswordChange */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** PipelineCounts */
        PipelineCounts: {
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Pending */
            pending: number;
            /** Running */
            running: number;
            /** Total */
            total: number;
        };
        /**
         * PipelineStage
         * @enum {string}
         */
        PipelineStage: "extract" | "metadata" | "batch_analysis" | "enrich" | "relationships" | "claims" | "entities" | "embeddings";
        /** ProfileUpdate */
        ProfileUpdate: {
            /**
             * Display Name
             * @default
             */
            display_name: string;
        };
        /** QueueCounts */
        QueueCounts: {
            /** Ai Inflight */
            ai_inflight: number;
            /** Executing */
            executing: number;
            /** Failed */
            failed: number;
            /** Queued */
            queued: number;
        };
        /** QueueItem */
        QueueItem: {
            /** Batch Id */
            batch_id: number | null;
            /** Doc Count */
            doc_count: number;
            /** Doc Id */
            doc_id: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "doc" | "batch";
            /** Label */
            label: string;
            stage: components["schemas"]["PipelineStage"];
        };
        /** QueueView */
        QueueView: {
            counts: components["schemas"]["QueueCounts"];
            /** Executing */
            executing: components["schemas"]["QueueItem"][];
            /** Failed */
            failed: components["schemas"]["FailedDoc"][];
            /** Queued */
            queued: components["schemas"]["QueueItem"][];
        };
        /** ReindexJob */
        ReindexJob: {
            /** Embed Dim */
            embed_dim?: number | null;
            /** Ended At */
            ended_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Reindexed
             * @default 0
             */
            reindexed: number;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "failed";
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * RoleHealthView
         * @description Live health per role; a separate call because it talks to the endpoints.
         */
        RoleHealthView: {
            chat: components["schemas"]["AiHealth"];
            embed: components["schemas"]["AiHealth"];
            ocr: components["schemas"]["AiHealth"];
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Instance Id */
            instance_id: string;
            /**
             * Model
             * @default
             */
            model: string;
        };
        /** RoleUpdateResult */
        RoleUpdateResult: {
            embed_index: components["schemas"]["EmbedIndex"];
            health: components["schemas"]["AiHealth"];
            role: components["schemas"]["AiRole"];
            /** Warning */
            warning: string | null;
        };
        /** SearchCase */
        SearchCase: {
            /** Id */
            id: string;
            status: components["schemas"]["CaseStatus"];
            /** Title */
            title: string;
        };
        /** SearchContact */
        SearchContact: {
            /** Name */
            name: string;
        };
        /** SearchDocument */
        SearchDocument: {
            /** Case Id */
            case_id: string | null;
            /** Id */
            id: number;
            /** Title */
            title: string;
        };
        /** SearchResults */
        SearchResults: {
            /** Cases */
            cases: components["schemas"]["SearchCase"][];
            /** Contacts */
            contacts: components["schemas"]["SearchContact"][];
            /** Documents */
            documents: components["schemas"]["SearchDocument"][];
            /** Total */
            total: number;
        };
        /**
         * SessionStarted
         * @description A session cookie was set; ``next`` is the same-site path to navigate to.
         */
        SessionStarted: {
            /** Next */
            next: string;
        };
        /**
         * ShellView
         * @description Everything the persistent app shell (rail, profile menu) renders.
         */
        ShellView: {
            /** Triage Count */
            triage_count: number;
            user: components["schemas"]["CurrentUser"];
        };
        /**
         * SignificanceTier
         * @description Document significance to case — drives graph visibility.
         * @enum {string}
         */
        SignificanceTier: "critical" | "significant" | "informational" | "administrative";
        /** SignupRequest */
        SignupRequest: {
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Password Confirm */
            password_confirm: string;
        };
        /** SignupToggle */
        SignupToggle: {
            /** Enabled */
            enabled: boolean;
        };
        /** ThemeUpdate */
        ThemeUpdate: {
            /**
             * Theme
             * @enum {string}
             */
            theme: "dark" | "light";
        };
        /** TimezoneUpdate */
        TimezoneUpdate: {
            /** Tz */
            tz: string;
        };
        /**
         * UserRole
         * @description Account role. Admins manage users, signup, and password resets.
         * @enum {string}
         */
        UserRole: "admin" | "user";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_set_signup_api_v1_admin_signup_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupToggle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_delete_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_toggle_active_api_v1_admin_users__user_id__active_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_reset_password_api_v1_admin_users__user_id__password_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminPasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_reassign_cases_api_v1_admin_users__user_id__reassign_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminReassignCases"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_set_user_role_api_v1_admin_users__user_id__role_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsersView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_auth_config_api_v1_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStarted"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStarted"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_cases_directory_api_v1_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasesDirectory"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_create_case_api_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseCreated"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_confirm_close_api_v1_cases__case_id__confirm_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_dismiss_close_api_v1_cases__case_id__dismiss_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_home_api_v1_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_review_all_api_v1_home_review_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_account_api_v1_settings_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_change_email_api_v1_settings_account_email_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_change_password_api_v1_settings_account_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_update_profile_api_v1_settings_account_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_ai_settings_api_v1_settings_ai_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSettingsView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_debug_redact_api_v1_settings_ai_debug_redact_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugRedactUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugRedactUpdate"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_set_engine_api_v1_settings_ai_extraction_engine_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractionEngineUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionEngineUpdate"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_role_health_api_v1_settings_ai_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleHealthView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_create_instance_api_v1_settings_ai_instances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiInstanceInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiInstance"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_update_instance_api_v1_settings_ai_instances__instance_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiInstanceInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiInstance"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_remove_instance_api_v1_settings_ai_instances__instance_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_instance_models_api_v1_settings_ai_instances__instance_id__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_test_instance_api_v1_settings_ai_instances__instance_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiHealth"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_ocr_concurrency_api_v1_settings_ai_ocr_concurrency_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConcurrencyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConcurrencyResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_rebuild_index_api_v1_settings_ai_rebuild_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexJob"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_reindex_api_v1_settings_ai_reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexJob"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_reindex_status_api_v1_settings_ai_reindex_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexJob"] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_set_role_api_v1_settings_ai_roles__role__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "chat" | "embed" | "ocr";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleUpdateResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_worker_concurrency_api_v1_settings_ai_worker_concurrency_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConcurrencyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConcurrencyResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_appearance_api_v1_settings_appearance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppearanceView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_save_dashboard_cards_api_v1_settings_appearance_dashboard_cards_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardCards"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppearanceView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_save_theme_api_v1_settings_appearance_theme_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThemeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppearanceView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_save_timezone_api_v1_settings_appearance_timezone_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimezoneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppearanceView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_data_api_v1_settings_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_clear_all_data_api_v1_settings_data_clear_all_data_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_debug_logs_api_v1_settings_data_debug_logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugLogList"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_debug_log_api_v1_settings_data_debug_logs_view_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugLogView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_export_api_v1_settings_data_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_reset_enrichment_api_v1_settings_data_reset_enrichment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_gmail_api_v1_settings_gmail_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_backfill_api_v1_settings_gmail_backfill_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GmailBackfill"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_save_filters_api_v1_settings_gmail_filters_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GmailFilters"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmailView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_identity_api_v1_settings_identity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_save_identity_api_v1_settings_identity_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityView"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_shell_api_v1_shell_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShellView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_worker_queue_api_v1_worker_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    v1_retry_failed_api_v1_worker_queue_retry_failed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
