"""add_scan_ingest_schema

Revision ID: 0efd2e9d5fc9
Revises: 2cd43f2bc460
Create Date: 2026-04-19 10:44:33.671873

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0efd2e9d5fc9"
down_revision: str | Sequence[str] | None = "2cd43f2bc460"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingest_batches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_hash", sa.String(), nullable=True))
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "AWAITING_SLICING",
                name="ingestbatchstatus",
            ),
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_ingest_batches_source_hash"), ["source_hash"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingest_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingest_batches_source_hash"))
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "AWAITING_SLICING",
                name="ingestbatchstatus",
            ),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )
        batch_op.drop_column("source_hash")

    # ### end Alembic commands ###
