"""add dismissed status to batch and documents

Revision ID: 124d074937a0
Revises: d4e5f6a7b8c1
Create Date: 2026-04-29 16:36:19.965331

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "124d074937a0"
down_revision: str | Sequence[str] | None = "d4e5f6a7b8c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_conversation_id"),
            ["conversation_id"],
            unique=False,
        )

    with op.batch_alter_table("document_relationships", schema=None) as batch_op:
        batch_op.drop_index("uq_document_relationships_edge")
        batch_op.create_unique_constraint(
            "uq_document_relationships_edge",
            ["from_document_id", "to_document_id", "relationship_type"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_relationships", schema=None) as batch_op:
        batch_op.drop_constraint("uq_document_relationships_edge", type_="unique")
        batch_op.create_index(
            "uq_document_relationships_edge",
            ["from_document_id", "to_document_id", "relationship_type"],
            unique=1,
        )

    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_messages_conversation_id"))

    # ### end Alembic commands ###
