"""add embedding_failed_at to claims

Revision ID: 1709cde45dde
Revises: d59aa2f89125
Create Date: 2026-05-22 18:47:26.310460

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1709cde45dde"
down_revision: str | Sequence[str] | None = "d59aa2f89125"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("embedding_failed_at", sa.DateTime(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_claims_embedding_failed_at"),
            ["embedding_failed_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claims_embedding_failed_at"))
        batch_op.drop_column("embedding_failed_at")

    # ### end Alembic commands ###
