"""add dismissed status to batch and documents

Revision ID: 19a766eefe1b
Revises: d4e5f6a7b8c1
Create Date: 2026-04-29 17:30:46.803630

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19a766eefe1b"
down_revision: str | Sequence[str] | None = "d4e5f6a7b8c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("ACTIVE", "DISMISSED", name="documentstatus"),
                nullable=False,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_documents_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_status"))
        batch_op.drop_column("status")

    # ### end Alembic commands ###
