"""Add original_filename to Document

Revision ID: 3e4ccd63e8be
Revises: 6cd31318d354
Create Date: 2026-05-11 10:14:03.874613

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e4ccd63e8be"
down_revision: str | Sequence[str] | None = "6cd31318d354"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("claim_evidence_proposals", schema=None) as batch_op:
        batch_op.alter_column(
            "proposed_role",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum(
                "ASSERTS",
                "SUPPORTS",
                "CONTESTS",
                "REFUTES",
                "CITES_AS_PROOF",
                name="claimevidencerole",
            ),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "confidence",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum("HIGH", "MEDIUM", "LOW", name="proposalconfidence"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum("PENDING", "CONFIRMED", "DISMISSED", name="proposalstatus"),
            existing_nullable=False,
            existing_server_default=sa.text("'PENDING'"),
        )
        batch_op.create_index(
            batch_op.f("ix_claim_evidence_proposals_id"), ["id"], unique=False
        )

    with op.batch_alter_table("claim_merge_proposals", schema=None) as batch_op:
        batch_op.alter_column(
            "confidence",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Enum("HIGH", "MEDIUM", "LOW", name="proposalconfidence"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum("PENDING", "CONFIRMED", "DISMISSED", name="proposalstatus"),
            existing_nullable=False,
            existing_server_default=sa.text("'PENDING'"),
        )
        batch_op.create_index(
            batch_op.f("ix_claim_merge_proposals_id"), ["id"], unique=False
        )

    with op.batch_alter_table("document_relationships", schema=None) as batch_op:
        batch_op.drop_index("uq_document_relationships_edge")
        batch_op.create_unique_constraint(
            "uq_document_relationships_edge",
            ["from_document_id", "to_document_id", "relationship_type"],
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("original_filename", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_column("original_filename")

    with op.batch_alter_table("document_relationships", schema=None) as batch_op:
        batch_op.drop_constraint("uq_document_relationships_edge", type_="unique")
        batch_op.create_index(
            "uq_document_relationships_edge",
            ["from_document_id", "to_document_id", "relationship_type"],
            unique=1,
        )

    with op.batch_alter_table("claim_merge_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_merge_proposals_id"))
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "PENDING", "CONFIRMED", "DISMISSED", name="proposalstatus"
            ),
            type_=sa.VARCHAR(length=12),
            existing_nullable=False,
            existing_server_default=sa.text("'PENDING'"),
        )
        batch_op.alter_column(
            "confidence",
            existing_type=sa.Enum("HIGH", "MEDIUM", "LOW", name="proposalconfidence"),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    with op.batch_alter_table("claim_evidence_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_claim_evidence_proposals_id"))
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "PENDING", "CONFIRMED", "DISMISSED", name="proposalstatus"
            ),
            type_=sa.VARCHAR(length=12),
            existing_nullable=False,
            existing_server_default=sa.text("'PENDING'"),
        )
        batch_op.alter_column(
            "confidence",
            existing_type=sa.Enum("HIGH", "MEDIUM", "LOW", name="proposalconfidence"),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "proposed_role",
            existing_type=sa.Enum(
                "ASSERTS",
                "SUPPORTS",
                "CONTESTS",
                "REFUTES",
                "CITES_AS_PROOF",
                name="claimevidencerole",
            ),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
