"""add_extraction_confidence_to_documents

Revision ID: 5077ebd5d13d
Revises: ee321e4b1674
Create Date: 2026-04-06 02:10:40.839947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5077ebd5d13d'
down_revision: Union[str, Sequence[str], None] = 'ee321e4b1674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extraction_confidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extraction_confidence')
    # ### end Alembic commands ###
