"""add proceeding_id to legal_costs

Revision ID: 5440cdef505b
Revises: ca45aaa94f30
Create Date: 2026-04-26 11:28:48.964073

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5440cdef505b"
down_revision: str | Sequence[str] | None = "ca45aaa94f30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("document_vectors_info")
    op.drop_table("document_vectors_vector_chunks00")
    with op.batch_alter_table("document_vectors", schema=None) as batch_op:
        batch_op.drop_index("sqlite_butoindex_x_1")

    op.drop_table("document_vectors")
    op.drop_table("document_vectors_chunks")
    op.drop_table("document_vectors_rowids")
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.drop_index("ix_action_items_source_document")

    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.drop_index("ix_claims_source_document")

    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_messages_conversation_id"),
            ["conversation_id"],
            unique=False,
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "pipeline_state",
            existing_type=sa.VARCHAR(length=16),
            type_=sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "partial",
                name="pipelinestate",
            ),
            existing_nullable=False,
            existing_server_default=sa.text("'pending'"),
        )

    with op.batch_alter_table("legal_costs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proceeding_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            "ix_legal_costs_case_proceeding", ["case_id", "proceeding_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_legal_costs_proceeding_id"), ["proceeding_id"], unique=False
        )
        batch_op.create_foreign_key(None, "proceedings", ["proceeding_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("legal_costs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_legal_costs_proceeding_id"))
        batch_op.drop_index("ix_legal_costs_case_proceeding")
        batch_op.drop_column("proceeding_id")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "pipeline_state",
            existing_type=sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "partial",
                name="pipelinestate",
            ),
            type_=sa.VARCHAR(length=16),
            existing_nullable=False,
            existing_server_default=sa.text("'pending'"),
        )

    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_messages_conversation_id"))

    with op.batch_alter_table("claims", schema=None) as batch_op:
        batch_op.create_index(
            "ix_claims_source_document", ["source_document_id"], unique=False
        )

    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_action_items_source_document", ["source_document_id"], unique=False
        )

    op.create_table(
        "document_vectors_rowids",
        sa.Column("rowid", sa.INTEGER(), nullable=True),
        sa.Column("id", sa.NullType(), nullable=True),
        sa.Column("chunk_id", sa.INTEGER(), nullable=True),
        sa.Column("chunk_offset", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.create_table(
        "document_vectors_chunks",
        sa.Column("chunk_id", sa.INTEGER(), nullable=True),
        sa.Column("size", sa.INTEGER(), nullable=False),
        sa.Column("validity", sa.BLOB(), nullable=False),
        sa.Column("rowids", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("chunk_id"),
    )
    op.create_table(
        "document_vectors",
        sa.Column("document_id", sa.NullType(), nullable=False),
        sa.Column("embedding", sa.NullType(), nullable=True),
        sa.PrimaryKeyConstraint("document_id"),
    )
    with op.batch_alter_table("document_vectors", schema=None) as batch_op:
        batch_op.create_index("sqlite_butoindex_x_1", [], unique=1)

    op.create_table(
        "document_vectors_vector_chunks00",
        sa.Column("rowid", sa.NullType(), nullable=True),
        sa.Column("vectors", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("rowid"),
    )
    op.create_table(
        "document_vectors_info",
        sa.Column("key", sa.TEXT(), nullable=True),
        sa.Column("value", sa.NUMERIC(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###
