"""add proceeding_id to legal_costs

Revision ID: 5440cdef505b
Revises: ca45aaa94f30
Create Date: 2026-04-26 11:28:48.964073

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5440cdef505b"
down_revision: str | Sequence[str] | None = "ca45aaa94f30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "pipeline_state",
            existing_type=sa.VARCHAR(length=16),
            type_=sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "partial",
                name="pipelinestate",
            ),
            existing_nullable=False,
            existing_server_default=sa.text("'pending'"),
        )

    with op.batch_alter_table("legal_costs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proceeding_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            "ix_legal_costs_case_proceeding", ["case_id", "proceeding_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_legal_costs_proceeding_id"), ["proceeding_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_legal_costs_proceeding_id", "proceedings", ["proceeding_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("legal_costs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_legal_costs_proceeding_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_legal_costs_proceeding_id"))
        batch_op.drop_index("ix_legal_costs_case_proceeding")
        batch_op.drop_column("proceeding_id")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.alter_column(
            "pipeline_state",
            existing_type=sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "partial",
                name="pipelinestate",
            ),
            type_=sa.VARCHAR(length=16),
            existing_nullable=False,
            existing_server_default=sa.text("'pending'"),
        )

    # ### end Alembic commands ###
