"""add_attachment_manifest_email_note_to_ingest_batch

Revision ID: 68953086cfe8
Revises: 460a2a27f371
Create Date: 2026-05-27 17:16:23.360059

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68953086cfe8"
down_revision: str | Sequence[str] | None = "460a2a27f371"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingest_batches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("attachment_manifest", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("email_note", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingest_batches", schema=None) as batch_op:
        batch_op.drop_column("email_note")
        batch_op.drop_column("attachment_manifest")

    # ### end Alembic commands ###
