"""add_case_opposing_parties

Revision ID: 697d2604431a
Revises: 6233c7a3800c
Create Date: 2026-05-17 15:46:11.940589

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "697d2604431a"
down_revision: str | Sequence[str] | None = "6233c7a3800c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.drop_index("uq_action_items_case_due_type")
        batch_op.create_unique_constraint(
            "uq_action_items_case_due_type", ["case_id", "due_date", "action_type"]
        )

    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("opposing_parties", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_column("opposing_parties")

    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.drop_constraint("uq_action_items_case_due_type", type_="unique")
        batch_op.create_index(
            "uq_action_items_case_due_type",
            ["case_id", "due_date", "action_type"],
            unique=1,
        )

    # ### end Alembic commands ###
