"""drop_conversation_tables

Revision ID: 7ffe9c4d9e2e
Revises: ef3a70ca6ad7
Create Date: 2026-04-22 09:23:29.981893

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "7ffe9c4d9e2e"
down_revision: str | Sequence[str] | None = "ef3a70ca6ad7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index("ix_conversations_id")
        batch_op.drop_index("ix_conversations_scope")

    op.drop_table("conversations")
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_conversation_messages_conversation")
        batch_op.drop_index("ix_conversation_messages_conversation_id")
        batch_op.drop_index("ix_conversation_messages_id")

    op.drop_table("conversation_messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("conversation_id", sa.INTEGER(), nullable=False),
        sa.Column("role", sa.VARCHAR(length=9), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("context_document_ids", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.create_index("ix_conversation_messages_id", ["id"], unique=False)
        batch_op.create_index(
            "ix_conversation_messages_conversation_id",
            ["conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_conversation_messages_conversation", ["conversation_id"], unique=False
        )

    op.create_table(
        "conversations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("scope_type", sa.VARCHAR(length=8), nullable=False),
        sa.Column("scope_id", sa.VARCHAR(), nullable=False),
        sa.Column("title", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_conversations_scope", ["scope_type", "scope_id"], unique=False
        )
        batch_op.create_index("ix_conversations_id", ["id"], unique=False)

    # ### end Alembic commands ###
