"""add pending_close to case

Revision ID: 83bd889b7e6a
Revises: cdf763efb126
Create Date: 2026-05-21 17:51:59.092812

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83bd889b7e6a"
down_revision: str | Sequence[str] | None = "cdf763efb126"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pending_close",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_column("pending_close")

    # ### end Alembic commands ###
