"""add_ai_approval_fields

Revision ID: 8f467fcb0f13
Revises: 5077ebd5d13d
Create Date: 2026-04-06 02:13:27.743861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f467fcb0f13'
down_revision: Union[str, Sequence[str], None] = '5077ebd5d13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ai_summary_approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ai_summary_approved_at')
    # ### end Alembic commands ###
