"""Add database indexes

Revision ID: 9e4cfaaa0c42
Revises: ed8df31d8955
Create Date: 2026-04-15 17:48:57.723650

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e4cfaaa0c42"
down_revision: str | Sequence[str] | None = "ed8df31d8955"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_documents_parent_id"), "documents", ["parent_id"], unique=False
    )
    op.create_index(op.f("ix_documents_sender"), "documents", ["sender"], unique=False)
    op.create_index(
        op.f("ix_legal_costs_due_at"), "legal_costs", ["due_at"], unique=False
    )
    op.create_index(
        op.f("ix_legal_costs_issued_at"), "legal_costs", ["issued_at"], unique=False
    )
    op.create_index(
        op.f("ix_legal_costs_paid_at"), "legal_costs", ["paid_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_legal_costs_paid_at"), table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_issued_at"), table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_due_at"), table_name="legal_costs")
    op.drop_index(op.f("ix_documents_sender"), table_name="documents")
    op.drop_index(op.f("ix_documents_parent_id"), table_name="documents")
    # ### end Alembic commands ###
