"""add_cost_candidates_to_documents

Revision ID: 9ed2e0c45310
Revises: 9f86d081884c
Create Date: 2026-04-06 01:29:10.706740

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ed2e0c45310"
down_revision: str | Sequence[str] | None = "9f86d081884c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("cost_candidates", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "cost_candidates")
    # ### end Alembic commands ###
