"""initial baseline (postgres)

Revision ID: b9fafd2f3daf
Revises:
Create Date: 2026-07-12 12:23:19.641040

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b9fafd2f3daf"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before any `vector(N)` column below can be created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "settings_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "claims",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column(
            "claim_type",
            sa.Enum(
                "FACTUAL", "LEGAL", "PROCEDURAL", name="claimtype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ASSERTED",
                "CONTESTED",
                "NEEDS_PROOF",
                "REFUTED",
                "ESTABLISHED",
                name="claimstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_precedent", sa.Boolean(), nullable=False),
        sa.Column("first_made_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("embedding_failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_claims_dismissed_at"), "claims", ["dismissed_at"], unique=False
    )
    op.create_index(
        op.f("ix_claims_embedding_failed_at"),
        "claims",
        ["embedding_failed_at"],
        unique=False,
    )
    op.create_index(op.f("ix_claims_id"), "claims", ["id"], unique=False)
    op.create_index("ix_claims_status", "claims", ["status"], unique=False)
    op.create_index(
        "ix_claims_embedding_hnsw",
        "claims",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "USER", name="userrole", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("oidc_subject", sa.String(), nullable=True),
        sa.Column("oidc_issuer", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "oidc_issuer", "oidc_subject", name="uq_users_oidc_identity"
        ),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_users_oidc_subject"), "users", ["oidc_subject"], unique=False
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_label", sa.String(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "CASE_DELETED",
                "DOCUMENT_DELETED",
                "AI_INSTANCE_CREATED",
                "AI_INSTANCE_UPDATED",
                "AI_INSTANCE_DELETED",
                "AI_ACTIVE_CHANGED",
                "AI_USER_CONTEXT_CHANGED",
                "SETTINGS_THEME_CHANGED",
                "SETTINGS_DASHBOARD_CARDS_CHANGED",
                "SETTINGS_TIMEZONE_CHANGED",
                "SETTINGS_PARTIES_CHANGED",
                "SETTINGS_INGESTION_CHANGED",
                "SETTINGS_WORKERS_CHANGED",
                "MAINTENANCE_RESET_AI_ENRICHMENT",
                "MAINTENANCE_CLEAR_ALL_DATA",
                "MAINTENANCE_REBUILD_INDEX",
                "MAINTENANCE_REINDEX_DOCUMENTS",
                "AI_DEBUG_REDACT_TOGGLED",
                "CASE_PURGED",
                "DATA_EXPORTED",
                name="auditeventtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("target_type", sa.String(), nullable=True),
        sa.Column("target_id", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"),
        "audit_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False
    )
    op.create_table(
        "cases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "INTAKE",
                "DISCOVERY",
                "PRE_TRIAL",
                "TRIAL",
                "POST_TRIAL",
                "CLOSED",
                name="casestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "jurisdiction",
            sa.Enum("DE", "UK", "US", "OTHER", name="jurisdiction", native_enum=False),
            nullable=False,
        ),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("pending_close", sa.Boolean(), nullable=False),
        sa.Column(
            "case_type",
            sa.Enum(
                "CIVIL",
                "FAMILY",
                "ADMINISTRATIVE",
                "CRIMINAL",
                name="casetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("assume_worst_case", sa.Boolean(), nullable=False),
        sa.Column("ai_brief", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ai_brief_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("brief_queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "opposing_parties", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("total_cost_exposure", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cases_brief_queued_at"), "cases", ["brief_queued_at"], unique=False
    )
    op.create_index(op.f("ix_cases_id"), "cases", ["id"], unique=False)
    op.create_index(op.f("ix_cases_owner_id"), "cases", ["owner_id"], unique=False)
    op.create_table(
        "claim_merge_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("new_claim_id", sa.Integer(), nullable=False),
        sa.Column("existing_claim_id", sa.Integer(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "HIGH", "MEDIUM", "LOW", name="proposalconfidence", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "DISMISSED",
                name="proposalstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["existing_claim_id"], ["claims.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["new_claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_claim_merge_proposals_existing_claim",
        "claim_merge_proposals",
        ["existing_claim_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_merge_proposals_id"),
        "claim_merge_proposals",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_claim_merge_proposals_new_claim",
        "claim_merge_proposals",
        ["new_claim_id"],
        unique=False,
    )
    op.create_index(
        "ix_claim_merge_proposals_status_pending",
        "claim_merge_proposals",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.Column("scope_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversations_id"), "conversations", ["id"], unique=False)
    op.create_index(
        "ix_conversations_scope",
        "conversations",
        ["scope_type", "scope_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False
    )
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "settings_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=True
    )
    op.create_table(
        "case_shares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "permission",
            sa.Enum("VIEWER", "EDITOR", name="caseaccesslevel", native_enum=False),
            nullable=False,
        ),
        sa.Column("granted_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "user_id", name="uq_case_shares_case_user"),
    )
    op.create_index("ix_case_shares_case", "case_shares", ["case_id"], unique=False)
    op.create_index(op.f("ix_case_shares_id"), "case_shares", ["id"], unique=False)
    op.create_index("ix_case_shares_user", "case_shares", ["user_id"], unique=False)
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "context_document_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conversation_messages_conversation",
        "conversation_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_messages_conversation_id"),
        "conversation_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_messages_id"),
        "conversation_messages",
        ["id"],
        unique=False,
    )
    op.create_table(
        "proceedings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("court_name", sa.String(), nullable=False),
        sa.Column(
            "court_level",
            sa.Enum(
                "AG",
                "LG",
                "OLG",
                "BGH",
                "OTHER",
                name="proceedingcourtlevel",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("subject_matter", sa.String(), nullable=True),
        sa.Column("az_court", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CLOSED", name="proceedingstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_proceedings_case", "proceedings", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_proceedings_case_id"), "proceedings", ["case_id"], unique=False
    )
    op.create_index(
        "ix_proceedings_case_status", "proceedings", ["case_id", "status"], unique=False
    )
    op.create_index(op.f("ix_proceedings_id"), "proceedings", ["id"], unique=False)
    op.create_table(
        "ingest_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "EMAIL",
                "SCAN",
                "MANUAL",
                name="ingestbatchsourcetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sender_email", sa.String(), nullable=True),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("raw_source_path", sa.String(), nullable=True),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.Column("case_id", sa.String(), nullable=True),
        sa.Column("proceeding_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "DISMISSED",
                "AWAITING_SLICING",
                name="ingestbatchstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("analysis_queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata_phase_queued_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("source_hash", sa.String(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "detected_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "attachment_manifest",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("email_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["proceeding_id"], ["proceedings.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingest_batches_case", "ingest_batches", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_batches_case_id"), "ingest_batches", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_batches_id"), "ingest_batches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_batches_message_id"),
        "ingest_batches",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingest_batches_owner_id"), "ingest_batches", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_batches_proceeding_id"),
        "ingest_batches",
        ["proceeding_id"],
        unique=False,
    )
    op.create_index(
        "ix_ingest_batches_received", "ingest_batches", ["received_at"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_batches_source_hash"),
        "ingest_batches",
        ["source_hash"],
        unique=False,
    )
    op.create_table(
        "batch_sub_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["ingest_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_batch_sub_groups_batch", "batch_sub_groups", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_batch_sub_groups_batch_id"),
        "batch_sub_groups",
        ["batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_batch_sub_groups_id"), "batch_sub_groups", ["id"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("case_id", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("original_filename", sa.String(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "originator_type",
            sa.Enum(
                "COURT",
                "OPPOSING",
                "OWN",
                "THIRD_PARTY",
                "UNKNOWN",
                name="originatortype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("internal_id", sa.String(), nullable=True),
        sa.Column("az_court", sa.String(), nullable=True),
        sa.Column("sender", sa.String(), nullable=True),
        sa.Column("received_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISMISSED", name="documentstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "review_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "pipeline_state",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "failed",
                "dismissed",
                "partial",
                name="pipelinestate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ai_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ai_summary_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_summary_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cost_candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "extraction_confidence",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("sub_group_id", sa.Integer(), nullable=True),
        sa.Column("sub_group_sort_order", sa.Integer(), nullable=True),
        sa.Column("ingest_batch_id", sa.Integer(), nullable=True),
        sa.Column("proceeding_id", sa.Integer(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "COVER_LETTER",
                "ENCLOSURE",
                "STANDALONE",
                name="documentrole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("court_relay", sa.Boolean(), nullable=False),
        sa.Column("attributed_originator", sa.String(), nullable=True),
        sa.Column(
            "document_type",
            sa.Enum(
                "RULING",
                "MOTION",
                "STATEMENT",
                "ANNEX",
                "RELAY",
                "CORRESPONDENCE",
                "REPORT",
                "INVOICE",
                "OTHER",
                name="documenttype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "significance_tier",
            sa.Enum(
                "CRITICAL",
                "SIGNIFICANT",
                "INFORMATIONAL",
                "ADMINISTRATIVE",
                name="significancetier",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("thread_open", sa.Boolean(), nullable=False),
        sa.Column(
            "key_passages", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["ingest_batch_id"], ["ingest_batches.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["proceeding_id"], ["proceedings.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["sub_group_id"], ["batch_sub_groups.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documents_az_court"), "documents", ["az_court"], unique=False
    )
    op.create_index(
        "ix_documents_case_created",
        "documents",
        ["case_id", "ingest_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False
    )
    op.create_index(
        "ix_documents_case_needs_review",
        "documents",
        ["case_id", "needs_review"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.create_index(
        "ix_documents_ingest_batch", "documents", ["ingest_batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_ingest_batch_id"),
        "documents",
        ["ingest_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_internal_id"), "documents", ["internal_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_issued_date"), "documents", ["issued_date"], unique=False
    )
    op.create_index(
        op.f("ix_documents_needs_review"), "documents", ["needs_review"], unique=False
    )
    op.create_index(
        "ix_documents_needs_review_created",
        "documents",
        ["needs_review", "ingest_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documents_owner_id"), "documents", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_parent_id"), "documents", ["parent_id"], unique=False
    )
    op.create_index(
        "ix_documents_pipeline_state", "documents", ["pipeline_state"], unique=False
    )
    op.create_index(
        "ix_documents_proceeding", "documents", ["proceeding_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_proceeding_id"), "documents", ["proceeding_id"], unique=False
    )
    op.create_index(op.f("ix_documents_sender"), "documents", ["sender"], unique=False)
    op.create_index(
        "ix_documents_significance", "documents", ["significance_tier"], unique=False
    )
    op.create_index(
        op.f("ix_documents_significance_tier"),
        "documents",
        ["significance_tier"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_index(
        "ix_documents_sub_group", "documents", ["sub_group_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_sub_group_id"), "documents", ["sub_group_id"], unique=False
    )
    op.create_index(op.f("ix_documents_title"), "documents", ["title"], unique=False)
    op.create_table(
        "action_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("proceeding_id", sa.Integer(), nullable=True),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "DEADLINE",
                "COURT_DATE",
                "RESPONSE_REQUIRED",
                "FILING_REQUIRED",
                "PAYMENT_DUE",
                name="actionitemtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "COMPLETED",
                "DISMISSED",
                name="actionitemstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("addressee", sa.String(), nullable=True),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["proceeding_id"], ["proceedings.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "case_id", "due_date", "action_type", name="uq_action_items_case_due_type"
        ),
    )
    op.create_index(
        "ix_action_items_case_due",
        "action_items",
        ["case_id", "due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_items_case_id"), "action_items", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_action_items_due_date"), "action_items", ["due_date"], unique=False
    )
    op.create_index(
        "ix_action_items_due_status",
        "action_items",
        ["due_date", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_action_items_id"), "action_items", ["id"], unique=False)
    op.create_index(
        "ix_action_items_proceeding", "action_items", ["proceeding_id"], unique=False
    )
    op.create_index(
        op.f("ix_action_items_proceeding_id"),
        "action_items",
        ["proceeding_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_action_items_source_document_id"),
        "action_items",
        ["source_document_id"],
        unique=False,
    )
    op.create_table(
        "claim_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("claim_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ASSERTS",
                "SUPPORTS",
                "CONTESTS",
                "REFUTES",
                "CITES_AS_PROOF",
                name="claimevidencerole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum(
                "AI_DETECTED",
                "USER_CONFIRMED",
                "USER_CREATED",
                name="relationshipconfidence",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_claim_evidence_claim", "claim_evidence", ["claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_claim_evidence_claim_id"), "claim_evidence", ["claim_id"], unique=False
    )
    op.create_index(
        "ix_claim_evidence_document", "claim_evidence", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_claim_evidence_document_id"),
        "claim_evidence",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_claim_evidence_id"), "claim_evidence", ["id"], unique=False
    )
    op.create_table(
        "claim_evidence_proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_claim_id", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=False),
        sa.Column(
            "proposed_role",
            sa.Enum(
                "ASSERTS",
                "SUPPORTS",
                "CONTESTS",
                "REFUTES",
                "CITES_AS_PROOF",
                name="claimevidencerole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum(
                "HIGH", "MEDIUM", "LOW", name="proposalconfidence", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "DISMISSED",
                name="proposalstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("proposed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["target_claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_claim_evidence_proposals_id"),
        "claim_evidence_proposals",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_claim_evidence_proposals_source_document",
        "claim_evidence_proposals",
        ["source_document_id"],
        unique=False,
    )
    op.create_index(
        "ix_claim_evidence_proposals_status_pending",
        "claim_evidence_proposals",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_index(
        "ix_claim_evidence_proposals_target_claim",
        "claim_evidence_proposals",
        ["target_claim_id"],
        unique=False,
    )
    op.create_table(
        "cost_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("proceeding_id", sa.Integer(), nullable=True),
        sa.Column("source_document_id", sa.Integer(), nullable=False),
        sa.Column(
            "signal_type",
            sa.Enum(
                "streitwert",
                "cost_ruling",
                "pkh_grant",
                "pkh_denied",
                name="costsignaltype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("allocation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["proceeding_id"], ["proceedings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_document_id", "signal_type", name="uq_cost_signal_doc_type"
        ),
    )
    op.create_index(
        op.f("ix_cost_signals_case_id"), "cost_signals", ["case_id"], unique=False
    )
    op.create_index(op.f("ix_cost_signals_id"), "cost_signals", ["id"], unique=False)
    op.create_index(
        op.f("ix_cost_signals_issued_at"), "cost_signals", ["issued_at"], unique=False
    )
    op.create_index(
        "ix_cost_signals_proc_type",
        "cost_signals",
        ["proceeding_id", "signal_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_signals_proceeding_id"),
        "cost_signals",
        ["proceeding_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_signals_signal_type"),
        "cost_signals",
        ["signal_type"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_document_chunks_document", "document_chunks", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_id"), "document_chunks", ["id"], unique=False
    )
    op.create_index(
        "ix_document_chunks_embedding_hnsw",
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.create_table(
        "document_pins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("passage_id", sa.String(length=12), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_document_pins_document", "document_pins", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_pins_document_id"),
        "document_pins",
        ["document_id"],
        unique=False,
    )
    op.create_index(op.f("ix_document_pins_id"), "document_pins", ["id"], unique=False)
    op.create_index(
        "ix_document_pins_passage", "document_pins", ["passage_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_pins_user_id"), "document_pins", ["user_id"], unique=False
    )
    op.create_table(
        "document_pipeline_stages",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("next_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id", "stage"),
    )
    op.create_index(
        "ix_dps_stage_status",
        "document_pipeline_stages",
        ["stage", "status"],
        unique=False,
    )
    op.create_index(
        "ix_dps_status", "document_pipeline_stages", ["status"], unique=False
    )
    op.create_table(
        "document_relationships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_document_id", sa.Integer(), nullable=False),
        sa.Column("to_document_id", sa.Integer(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "REPLIES_TO",
                "REFERENCES",
                "ATTACHES_AS_PROOF",
                "SUPERSEDES",
                "CITED_BY",
                "ENCLOSES",
                name="relationshiptype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum(
                "AI_DETECTED",
                "USER_CONFIRMED",
                "USER_CREATED",
                name="relationshipconfidence",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_document_id"], ["documents.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["to_document_id"], ["documents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_document_id",
            "to_document_id",
            "relationship_type",
            name="uq_document_relationships_edge",
        ),
    )
    op.create_index(
        "ix_document_relationships_from",
        "document_relationships",
        ["from_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_relationships_from_document_id"),
        "document_relationships",
        ["from_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_relationships_id"),
        "document_relationships",
        ["id"],
        unique=False,
    )
    op.create_index(
        "ix_document_relationships_to",
        "document_relationships",
        ["to_document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_relationships_to_document_id"),
        "document_relationships",
        ["to_document_id"],
        unique=False,
    )
    op.create_index(
        "ix_document_relationships_type",
        "document_relationships",
        ["relationship_type"],
        unique=False,
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PERSON",
                "ORGANIZATION",
                "DATE",
                "FINANCIAL",
                "LEGAL_CATEGORY",
                "COURT",
                "LAW_FIRM",
                "CITATION",
                name="entitytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entities_case_id"), "entities", ["case_id"], unique=False)
    op.create_index(
        "ix_entities_case_type", "entities", ["case_id", "type"], unique=False
    )
    op.create_index(op.f("ix_entities_id"), "entities", ["id"], unique=False)
    op.create_index(op.f("ix_entities_name"), "entities", ["name"], unique=False)
    op.create_index(op.f("ix_entities_type"), "entities", ["type"], unique=False)
    op.create_table(
        "legal_costs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("proceeding_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "GERICHTSKOSTEN",
                "ANWALTSKOSTEN",
                "ANWALTSKOSTEN_GEGNER",
                "SACHVERSTAENDIGER",
                "VORSCHUSS",
                "VOLLSTRECKUNG",
                "AUSLAGEN",
                "SONSTIGES",
                name="costcategory",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OFFEN",
                "BEZAHLT",
                "ERSTATTET",
                "TEILWEISE",
                "STRITTIG",
                name="coststatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("rvg_position", sa.String(), nullable=True),
        sa.Column("amount_net", sa.Float(), nullable=False),
        sa.Column("vat_rate", sa.Float(), nullable=True),
        sa.Column("amount_gross", sa.Float(), nullable=False),
        sa.Column("amount_paid", sa.Float(), nullable=True),
        sa.Column("amount_reimbursed", sa.Float(), nullable=True),
        sa.Column("streitwert", sa.Float(), nullable=True),
        sa.Column("gebuehren_faktor", sa.Float(), nullable=True),
        sa.Column("is_reimbursable", sa.Boolean(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("offsets_cost_id", sa.Integer(), nullable=True),
        sa.Column("auto_created", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["offsets_cost_id"], ["legal_costs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["proceeding_id"],
            ["proceedings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_legal_costs_case_id"), "legal_costs", ["case_id"], unique=False
    )
    op.create_index(
        "ix_legal_costs_case_proceeding",
        "legal_costs",
        ["case_id", "proceeding_id"],
        unique=False,
    )
    op.create_index(
        "ix_legal_costs_case_status", "legal_costs", ["case_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_legal_costs_due_at"), "legal_costs", ["due_at"], unique=False
    )
    op.create_index(op.f("ix_legal_costs_id"), "legal_costs", ["id"], unique=False)
    op.create_index(
        op.f("ix_legal_costs_issued_at"), "legal_costs", ["issued_at"], unique=False
    )
    op.create_index(
        op.f("ix_legal_costs_offsets_cost_id"),
        "legal_costs",
        ["offsets_cost_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_costs_paid_at"), "legal_costs", ["paid_at"], unique=False
    )
    op.create_index(
        op.f("ix_legal_costs_proceeding_id"),
        "legal_costs",
        ["proceeding_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_costs_status"), "legal_costs", ["status"], unique=False
    )
    op.create_index(
        "ix_legal_costs_status_due", "legal_costs", ["status", "due_at"], unique=False
    )
    op.create_table(
        "user_reactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "reaction",
            sa.Enum(
                "LIES",
                "TRUE",
                "NEEDS_PROOF",
                "PRECEDENT",
                name="userreactiontype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("ingest_date", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_reactions_document", "user_reactions", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_reactions_document_id"),
        "user_reactions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_reactions_id"), "user_reactions", ["id"], unique=False
    )
    op.create_index(
        "ix_user_reactions_reaction", "user_reactions", ["reaction"], unique=False
    )
    op.create_index(
        op.f("ix_user_reactions_user_id"), "user_reactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_reactions_user_id"), table_name="user_reactions")
    op.drop_index("ix_user_reactions_reaction", table_name="user_reactions")
    op.drop_index(op.f("ix_user_reactions_id"), table_name="user_reactions")
    op.drop_index(op.f("ix_user_reactions_document_id"), table_name="user_reactions")
    op.drop_index("ix_user_reactions_document", table_name="user_reactions")
    op.drop_table("user_reactions")
    op.drop_index("ix_legal_costs_status_due", table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_status"), table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_proceeding_id"), table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_paid_at"), table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_offsets_cost_id"), table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_issued_at"), table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_id"), table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_due_at"), table_name="legal_costs")
    op.drop_index("ix_legal_costs_case_status", table_name="legal_costs")
    op.drop_index("ix_legal_costs_case_proceeding", table_name="legal_costs")
    op.drop_index(op.f("ix_legal_costs_case_id"), table_name="legal_costs")
    op.drop_table("legal_costs")
    op.drop_index(op.f("ix_entities_type"), table_name="entities")
    op.drop_index(op.f("ix_entities_name"), table_name="entities")
    op.drop_index(op.f("ix_entities_id"), table_name="entities")
    op.drop_index("ix_entities_case_type", table_name="entities")
    op.drop_index(op.f("ix_entities_case_id"), table_name="entities")
    op.drop_table("entities")
    op.drop_index("ix_document_relationships_type", table_name="document_relationships")
    op.drop_index(
        op.f("ix_document_relationships_to_document_id"),
        table_name="document_relationships",
    )
    op.drop_index("ix_document_relationships_to", table_name="document_relationships")
    op.drop_index(
        op.f("ix_document_relationships_id"), table_name="document_relationships"
    )
    op.drop_index(
        op.f("ix_document_relationships_from_document_id"),
        table_name="document_relationships",
    )
    op.drop_index("ix_document_relationships_from", table_name="document_relationships")
    op.drop_table("document_relationships")
    op.drop_index("ix_dps_status", table_name="document_pipeline_stages")
    op.drop_index("ix_dps_stage_status", table_name="document_pipeline_stages")
    op.drop_table("document_pipeline_stages")
    op.drop_index(op.f("ix_document_pins_user_id"), table_name="document_pins")
    op.drop_index("ix_document_pins_passage", table_name="document_pins")
    op.drop_index(op.f("ix_document_pins_id"), table_name="document_pins")
    op.drop_index(op.f("ix_document_pins_document_id"), table_name="document_pins")
    op.drop_index("ix_document_pins_document", table_name="document_pins")
    op.drop_table("document_pins")
    op.drop_index(op.f("ix_document_chunks_id"), table_name="document_chunks")
    op.drop_index("ix_document_chunks_document", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_cost_signals_signal_type"), table_name="cost_signals")
    op.drop_index(op.f("ix_cost_signals_proceeding_id"), table_name="cost_signals")
    op.drop_index("ix_cost_signals_proc_type", table_name="cost_signals")
    op.drop_index(op.f("ix_cost_signals_issued_at"), table_name="cost_signals")
    op.drop_index(op.f("ix_cost_signals_id"), table_name="cost_signals")
    op.drop_index(op.f("ix_cost_signals_case_id"), table_name="cost_signals")
    op.drop_table("cost_signals")
    op.drop_index(
        "ix_claim_evidence_proposals_target_claim",
        table_name="claim_evidence_proposals",
    )
    op.drop_index(
        "ix_claim_evidence_proposals_status_pending",
        table_name="claim_evidence_proposals",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index(
        "ix_claim_evidence_proposals_source_document",
        table_name="claim_evidence_proposals",
    )
    op.drop_index(
        op.f("ix_claim_evidence_proposals_id"), table_name="claim_evidence_proposals"
    )
    op.drop_table("claim_evidence_proposals")
    op.drop_index(op.f("ix_claim_evidence_id"), table_name="claim_evidence")
    op.drop_index(op.f("ix_claim_evidence_document_id"), table_name="claim_evidence")
    op.drop_index("ix_claim_evidence_document", table_name="claim_evidence")
    op.drop_index(op.f("ix_claim_evidence_claim_id"), table_name="claim_evidence")
    op.drop_index("ix_claim_evidence_claim", table_name="claim_evidence")
    op.drop_table("claim_evidence")
    op.drop_index(op.f("ix_action_items_source_document_id"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_proceeding_id"), table_name="action_items")
    op.drop_index("ix_action_items_proceeding", table_name="action_items")
    op.drop_index(op.f("ix_action_items_id"), table_name="action_items")
    op.drop_index("ix_action_items_due_status", table_name="action_items")
    op.drop_index(op.f("ix_action_items_due_date"), table_name="action_items")
    op.drop_index(op.f("ix_action_items_case_id"), table_name="action_items")
    op.drop_index("ix_action_items_case_due", table_name="action_items")
    op.drop_table("action_items")
    op.drop_index(op.f("ix_documents_title"), table_name="documents")
    op.drop_index(op.f("ix_documents_sub_group_id"), table_name="documents")
    op.drop_index("ix_documents_sub_group", table_name="documents")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_significance_tier"), table_name="documents")
    op.drop_index("ix_documents_significance", table_name="documents")
    op.drop_index(op.f("ix_documents_sender"), table_name="documents")
    op.drop_index(op.f("ix_documents_proceeding_id"), table_name="documents")
    op.drop_index("ix_documents_proceeding", table_name="documents")
    op.drop_index("ix_documents_pipeline_state", table_name="documents")
    op.drop_index(op.f("ix_documents_parent_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_owner_id"), table_name="documents")
    op.drop_index("ix_documents_needs_review_created", table_name="documents")
    op.drop_index(op.f("ix_documents_needs_review"), table_name="documents")
    op.drop_index(op.f("ix_documents_issued_date"), table_name="documents")
    op.drop_index(op.f("ix_documents_internal_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_ingest_batch_id"), table_name="documents")
    op.drop_index("ix_documents_ingest_batch", table_name="documents")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_index("ix_documents_case_needs_review", table_name="documents")
    op.drop_index(op.f("ix_documents_case_id"), table_name="documents")
    op.drop_index("ix_documents_case_created", table_name="documents")
    op.drop_index(op.f("ix_documents_az_court"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_batch_sub_groups_id"), table_name="batch_sub_groups")
    op.drop_index(op.f("ix_batch_sub_groups_batch_id"), table_name="batch_sub_groups")
    op.drop_index("ix_batch_sub_groups_batch", table_name="batch_sub_groups")
    op.drop_table("batch_sub_groups")
    op.drop_index(op.f("ix_ingest_batches_source_hash"), table_name="ingest_batches")
    op.drop_index("ix_ingest_batches_received", table_name="ingest_batches")
    op.drop_index(op.f("ix_ingest_batches_proceeding_id"), table_name="ingest_batches")
    op.drop_index(op.f("ix_ingest_batches_owner_id"), table_name="ingest_batches")
    op.drop_index(op.f("ix_ingest_batches_message_id"), table_name="ingest_batches")
    op.drop_index(op.f("ix_ingest_batches_id"), table_name="ingest_batches")
    op.drop_index(op.f("ix_ingest_batches_case_id"), table_name="ingest_batches")
    op.drop_index("ix_ingest_batches_case", table_name="ingest_batches")
    op.drop_table("ingest_batches")
    op.drop_index(op.f("ix_proceedings_id"), table_name="proceedings")
    op.drop_index("ix_proceedings_case_status", table_name="proceedings")
    op.drop_index(op.f("ix_proceedings_case_id"), table_name="proceedings")
    op.drop_index("ix_proceedings_case", table_name="proceedings")
    op.drop_table("proceedings")
    op.drop_index(
        op.f("ix_conversation_messages_id"), table_name="conversation_messages"
    )
    op.drop_index(
        op.f("ix_conversation_messages_conversation_id"),
        table_name="conversation_messages",
    )
    op.drop_index(
        "ix_conversation_messages_conversation", table_name="conversation_messages"
    )
    op.drop_table("conversation_messages")
    op.drop_index("ix_case_shares_user", table_name="case_shares")
    op.drop_index(op.f("ix_case_shares_id"), table_name="case_shares")
    op.drop_index("ix_case_shares_case", table_name="case_shares")
    op.drop_table("case_shares")
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index("ix_conversations_scope", table_name="conversations")
    op.drop_index(op.f("ix_conversations_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(
        "ix_claim_merge_proposals_status_pending",
        table_name="claim_merge_proposals",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index(
        "ix_claim_merge_proposals_new_claim", table_name="claim_merge_proposals"
    )
    op.drop_index(
        op.f("ix_claim_merge_proposals_id"), table_name="claim_merge_proposals"
    )
    op.drop_index(
        "ix_claim_merge_proposals_existing_claim", table_name="claim_merge_proposals"
    )
    op.drop_table("claim_merge_proposals")
    op.drop_index(op.f("ix_cases_owner_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_id"), table_name="cases")
    op.drop_index(op.f("ix_cases_brief_queued_at"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_oidc_subject"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_claims_status", table_name="claims")
    op.drop_index(op.f("ix_claims_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_embedding_failed_at"), table_name="claims")
    op.drop_index(op.f("ix_claims_dismissed_at"), table_name="claims")
    op.drop_table("claims")
    op.drop_table("app_settings")
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS vector")
