"""add brief_queued_at to cases

Revision ID: d59aa2f89125
Revises: 83bd889b7e6a
Create Date: 2026-05-22 17:17:32.228112

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d59aa2f89125"
down_revision: str | Sequence[str] | None = "83bd889b7e6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(sa.Column("brief_queued_at", sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_cases_brief_queued_at"), ["brief_queued_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cases_brief_queued_at"))
        batch_op.drop_column("brief_queued_at")

    # ### end Alembic commands ###
