"""add_batch_sub_groups

Revision ID: ed6760d9c7ab
Revises: 3e4ccd63e8be
Create Date: 2026-05-13 15:48:58.409842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed6760d9c7ab"
down_revision: str | Sequence[str] | None = "3e4ccd63e8be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_sub_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["ingest_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("batch_sub_groups", schema=None) as batch_op:
        batch_op.create_index("ix_batch_sub_groups_batch", ["batch_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_batch_sub_groups_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_batch_sub_groups_id"), ["id"], unique=False
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sub_group_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("sub_group_sort_order", sa.Integer(), nullable=True)
        )
        batch_op.create_index("ix_documents_sub_group", ["sub_group_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_documents_sub_group_id"), ["sub_group_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_documents_sub_group_id",
            "batch_sub_groups",
            ["sub_group_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint("fk_documents_sub_group_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_documents_sub_group_id"))
        batch_op.drop_index("ix_documents_sub_group")
        batch_op.drop_column("sub_group_sort_order")
        batch_op.drop_column("sub_group_id")

    with op.batch_alter_table("batch_sub_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_batch_sub_groups_id"))
        batch_op.drop_index(batch_op.f("ix_batch_sub_groups_batch_id"))
        batch_op.drop_index("ix_batch_sub_groups_batch")

    op.drop_table("batch_sub_groups")
    # ### end Alembic commands ###
