"""add_jurisdiction_to_cases

Revision ID: ed8df31d8955
Revises: 8f467fcb0f13
Create Date: 2026-04-06 02:21:20.214193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8df31d8955'
down_revision: Union[str, Sequence[str], None] = '8f467fcb0f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('jurisdiction', sa.Enum('DE', 'UK', 'US', 'OTHER', name='jurisdiction'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'jurisdiction')
    # ### end Alembic commands ###
