"""add_case_type_assume_worst_case_and_legal_cost_offset_fields

Revision ID: fef354f9b14f
Revises: 2298552222e2
Create Date: 2026-05-07 07:21:19.235363

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fef354f9b14f"
down_revision: str | Sequence[str] | None = "2298552222e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "case_type",
                sa.Enum(
                    "CIVIL", "FAMILY", "ADMINISTRATIVE", "CRIMINAL", name="casetype"
                ),
                nullable=False,
                server_default="CIVIL",
            )
        )
        batch_op.add_column(
            sa.Column(
                "assume_worst_case",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )

    with op.batch_alter_table("legal_costs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("offsets_cost_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "auto_created", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.create_index(
            batch_op.f("ix_legal_costs_offsets_cost_id"),
            ["offsets_cost_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_legal_costs_offsets_cost_id", "legal_costs", ["offsets_cost_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("legal_costs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_legal_costs_offsets_cost_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_legal_costs_offsets_cost_id"))
        batch_op.drop_column("auto_created")
        batch_op.drop_column("offsets_cost_id")

    with op.batch_alter_table("cases", schema=None) as batch_op:
        batch_op.drop_column("assume_worst_case")
        batch_op.drop_column("case_type")
    # ### end Alembic commands ###
