import type { Schemas } from '../api/client'

export const caseCard: Schemas['CaseCard'] = {
  id: 'ADV-024-A',
  title: 'Weber ./. Weber',
  status: 'pre_trial',
  status_label: 'Pre-Trial',
  is_draft: false,
  pending_close: false,
  can_edit: true,
  client_name: 'A. Weber',
  opposing_party: 'M. Weber',
  proceeding_name: 'AG Hamburg',
  matter_type: 'Sorgerecht',
  next_action: {
    title: 'File counter-statement',
    due_date: '2026-06-18T00:00:00Z',
    action_type: 'deadline',
  },
  exposure_eur: 18450,
  doc_count: 12,
  open_action_count: 1,
  new_docs: 2,
  days_since_activity: 3,
  is_dormant: false,
  max_significance: 'critical',
  last_activity_at: '2026-06-14T09:00:00Z',
}

export const shellView: Schemas['ShellView'] = {
  user: { id: 1, email: 'k.vogt@ra-vogt.de', display_name: 'Katharina Vogt', role: 'admin' },
  triage_count: 7,
}

export const emptyQueue: Schemas['QueueView'] = {
  counts: { executing: 0, queued: 0, failed: 0, ai_inflight: 0 },
  executing: [],
  queued: [],
  failed: [],
}

export const homeView: Schemas['HomeView'] = {
  greeting: 'Good morning',
  user_name: 'Katharina',
  now: '2026-06-17T06:40:00Z',
  today_items: [
    {
      id: 1,
      case_id: 'ADV-024-A',
      case_title: 'Weber ./. Weber',
      title: 'File counter-statement',
      description: null,
      due_date: '2026-06-18T00:00:00Z',
      action_type: 'deadline',
    },
  ],
  triage_bundles: [
    {
      id: 42,
      status: 'pending',
      received_at: '2026-06-21T09:12:00Z',
      sender_email: 'kanzlei-vogt@ra-vogt.de',
      title: 'Klageerwiderung',
      doc_count: 3,
      case_id: null,
      suggested_case_id: 'ADV-024-A',
      pipeline: { total: 3, running: 1, pending: 0, failed: 0, completed: 2 },
    },
  ],
  last_home_visit: '2026-06-16T08:00:00Z',
  delta_cases: [
    {
      case_id: 'ADV-019-C',
      case_title: 'Brandt GmbH ./. Keller',
      new_doc_count: 2,
      new_actions: 1,
      max_significance: 'significant',
      doc_titles: ['Lieferschein', 'Mahnung'],
    },
  ],
  signals: [
    {
      id: 'dormancy-1',
      kind: 'dormancy',
      severity: 'warn',
      title: 'Nachlass Hoffmann is dormant',
      detail: 'No document in 94 days.',
      action: 'check',
      link: '/cases/ADV-031-A',
    },
  ],
  draft_cases: [],
  activity: [
    {
      kind: 'document_enriched',
      title: 'Klageerwiderung.pdf',
      detail: 'ADV-024-A · Weber ./. Weber',
      occurred_at: '2026-06-17T06:32:00Z',
      case_id: 'ADV-024-A',
      link: '/document/2211',
    },
    {
      kind: 'pipeline_failed',
      title: 'Gutachten_Anhang_gross.pdf',
      detail: 'metadata stage · file too large',
      occurred_at: '2026-06-17T03:40:00Z',
      case_id: 'ADV-024-A',
      link: '/document/2212',
    },
  ],
  active_cases: [caseCard],
  caught_up: false,
}

export const aiSettings: Schemas['AiSettingsView'] = {
  instances: [
    {
      id: 'inst_a',
      label: 'Ollama · local',
      base_url: 'http://127.0.0.1:11434',
      has_api_key: false,
      is_external: false,
      summary_model: 'qwen3.5:9b',
      embed_model: 'nomic-embed-text',
      embed_dim: 768,
      ocr_model: '',
    },
    {
      id: 'inst_b',
      label: 'LM Studio · OCR',
      base_url: 'http://127.0.0.1:1234',
      has_api_key: true,
      is_external: false,
      summary_model: '',
      embed_model: '',
      embed_dim: null,
      ocr_model: 'chandra-ocr',
    },
  ],
  roles: [
    {
      role: 'chat',
      label: 'Chat',
      hint: 'Powers briefs.',
      active_id: 'inst_a',
      model: 'qwen3.5:9b',
      embed_dim: null,
    },
    {
      role: 'embed',
      label: 'Embeddings',
      hint: 'Powers search.',
      active_id: 'inst_a',
      model: 'nomic-embed-text',
      embed_dim: 768,
    },
    {
      role: 'ocr',
      label: 'OCR',
      hint: 'Reads scans.',
      active_id: 'inst_b',
      model: 'chandra-ocr',
      embed_dim: null,
    },
  ],
  extraction_engine: 'chandra',
  worker_concurrency: 2,
  ocr_concurrency: 4,
  embed_index: { dim: 768, model: 'nomic-embed-text', index_dim: 768, mismatch: false },
  reindex_job: null,
}

export const adminUsers: Schemas['AdminUsersView'] = {
  users: [
    {
      id: 1,
      email: 'k.vogt@ra-vogt.de',
      display_name: 'Katharina Vogt',
      role: 'admin',
      is_active: true,
      created_at: '2026-03-14T10:00:00Z',
      last_login_at: '2026-06-17T06:40:00Z',
      owned_case_count: 3,
    },
    {
      id: 2,
      email: 'reg@example.com',
      display_name: null,
      role: 'user',
      is_active: true,
      created_at: '2026-05-01T10:00:00Z',
      last_login_at: null,
      owned_case_count: 0,
    },
  ],
  signup_enabled: false,
}

export const triageBundle: Schemas['TriageBundle'] = {
  key: 'batch-42',
  batch_id: 42,
  is_synthetic: false,
  source_type: 'email',
  subject: 'Klageerwiderung',
  sender_email: 'kanzlei-vogt@ra-vogt.de',
  received_at: '2026-06-21T09:12:00Z',
  status: 'needs_review',
  pipeline_filter: 'ready',
  pipeline: { total: 3, counts: { completed: 3 }, active_label: null, failed_error: null },
  confirmed_case_id: null,
  suggestion: { case_id: 'ADV-024-A', title: 'Weber ./. Weber', is_draft: true, exists: true },
  proceeding: {
    id: 5,
    az_court: '003 F 426/25',
    court_name: 'Amtsgericht Hamburg',
    court_level: 'ag',
  },
  doc_count: 3,
  total_pages: 18,
  originator_types: ['opposing', 'court'],
  action_dates: [{ title: 'File counter-statement', due_date: '2026-06-18T00:00:00Z' }],
  has_manual_groups: false,
  has_unconfirmed_metadata: true,
  open_review_reasons: ['unresolved_relationship'],
  to_confirm_count: 2,
  lead_doc_id: 2211,
  documents: [
    {
      id: 2210,
      title: 'Begleitschreiben.pdf',
      role: 'cover_letter',
      depth: 0,
      originator_type: 'opposing',
      significance_tier: 'administrative',
      pipeline_state: 'completed',
      needs_review: false,
      review_reasons: [],
      page_count: 1,
      is_proof: false,
      sub_group_id: null,
    },
    {
      id: 2211,
      title: 'Klageerwiderung.pdf',
      role: 'enclosure',
      depth: 1,
      originator_type: 'opposing',
      significance_tier: 'critical',
      pipeline_state: 'completed',
      needs_review: true,
      review_reasons: ['missing_sender'],
      page_count: 12,
      is_proof: false,
      sub_group_id: null,
    },
    {
      id: 2212,
      title: 'Anlage B1.pdf',
      role: 'enclosure',
      depth: 1,
      originator_type: 'opposing',
      significance_tier: 'informational',
      pipeline_state: 'completed',
      needs_review: false,
      review_reasons: [],
      page_count: 5,
      is_proof: true,
      sub_group_id: null,
    },
  ],
  sub_groups: [
    {
      id: 'batch-42-g0',
      sub_group_id: null,
      label: 'Klageerwiderung.pdf',
      lead_doc_id: 2211,
      suggested_case_id: 'ADV-024-A',
      suggested_case_title: 'Weber ./. Weber',
      case_confidence: 'high',
      doc_ids: [2210, 2211, 2212],
    },
  ],
}

export const triageView: Schemas['TriageView'] = {
  bundles: [
    triageBundle,
    {
      ...triageBundle,
      key: 'batch-39',
      batch_id: 39,
      subject: 'Scan 214pp',
      status: 'stuck',
      pipeline_filter: 'failed',
      suggestion: null,
      proceeding: null,
      pipeline: {
        total: 1,
        counts: { failed: 1 },
        active_label: null,
        failed_error: 'Docling conversion failed — file too large.',
      },
      lead_doc_id: 3001,
      documents: triageBundle.documents.slice(0, 1),
      sub_groups: [],
    },
  ],
  stats: {
    pending: 2,
    needs_classification: 0,
    needs_review: 1,
    stuck: 1,
    processing: 0,
    failed_docs: 1,
    first_failed_doc_id: 3001,
    drafts_pending: 1,
    first_draft_doc_id: 2211,
  },
  filter_options: {
    cases: [{ value: 'ADV-024-A', label: 'ADV-024-A' }],
    proceedings: [],
    pipeline: [{ value: 'failed', label: 'Failed' }],
  },
  cases: [
    { id: 'ADV-024-A', title: 'Weber ./. Weber' },
    { id: 'ADV-019-C', title: 'Brandt GmbH ./. Keller' },
  ],
  proceedings: [{ id: 5, case_id: 'ADV-024-A', label: 'Amtsgericht Hamburg · 003 F 426/25' }],
  slicing_queue: [{ batch_id: 77, subject: 'scan.pdf', page_count: 9, status: 'ready' }],
}

export const documentReview: Schemas['DocumentReview'] = {
  id: 2211,
  title: 'Klageerwiderung.pdf',
  original_filename: 'Klageerwiderung.pdf',
  page_count: 12,
  case_id: '_TRIAGE',
  case: null,
  proceeding: null,
  originator_type: 'opposing',
  attributed_originator: null,
  court_relay: false,
  sender: null,
  internal_id: null,
  az_court: null,
  issued_date: '2026-06-14T00:00:00Z',
  received_date: '2026-06-21T00:00:00Z',
  ingest_date: '2026-06-21T09:12:00Z',
  document_type: 'statement',
  significance_tier: 'critical',
  needs_review: true,
  review_reasons: ['missing_sender'],
  content_hash: '3f9a…c412',
  metadata: [
    { field: 'originator_type', label: 'Originator', value: 'opposing', confidence: 'high' },
    { field: 'sender', label: 'Sender', value: null, confidence: 'low' },
    { field: 'issued_date', label: 'Issued', value: '2026-06-14', confidence: 'medium' },
  ],
  pipeline: {
    ocr_page_failures: [],
    state: 'completed',
    stages: [
      {
        key: 'extract',
        label: 'Extract',
        icon: 'file_upload',
        status: 'completed',
        error: null,
        attempt: null,
        max_attempts: null,
        next_at: null,
        completed_at: null,
      },
      {
        key: 'enrich',
        label: 'Enrich',
        icon: 'auto_fix_high',
        status: 'failed',
        error: 'LLM timeout',
        attempt: 3,
        max_attempts: 3,
        next_at: null,
        completed_at: null,
      },
    ],
  },
  summary: {
    bullets: [
      { kind: 'legal', text: 'Directly rebuts the core custody claim.' },
      { kind: 'action', text: 'File counter-statement before 18 Jun.' },
    ],
    approved_at: null,
    created_at: '2026-06-21T10:00:00Z',
    enrich_status: 'completed',
  },
  key_passages: [
    {
      id: 'p1',
      text: 'Der Beklagte bestreitet',
      kind: 'disputed factual claim',
      page: 2,
      rationale: null,
      start_offset: 10,
      end_offset: 40,
      claim_id: 9,
      pin_count: 0,
    },
  ],
  relationships: [
    {
      id: 501,
      doc_id: 1500,
      title: 'Antragsschrift',
      originator_type: 'court',
      rel_type: 'replies_to',
      confidence: 'ai_detected',
      direction: 'out',
    },
  ],
  grounds: [
    {
      id: 9,
      claim_text: 'Umgang wurde verweigert',
      claim_type: 'factual',
      status: 'contested',
      is_precedent: false,
      first_made_at: '2026-06-14T00:00:00Z',
    },
  ],
  evidence_proposals: [
    {
      proposal_id: 31,
      proposed_role: 'contests',
      excerpt: 'Der Umgang wurde nie verweigert.',
      target_claim_id: 9,
      target_claim_text: 'Umgang wurde nie gewährt',
      target_claim_status: 'asserted',
      source_document_id: 2211,
      source_document_title: 'Klageerwiderung.pdf',
    },
  ],
  contradiction_notes: [],
  claims_status: 'ran',
  actions: [
    {
      id: 77,
      title: 'File counter-statement',
      description: null,
      due_date: '2026-06-18T00:00:00Z',
      action_type: 'deadline',
      status: 'open',
      location: null,
      addressee: 'user',
    },
  ],
  cost_signals: [
    {
      id: 3,
      signal_type: 'streitwert',
      amount: 1240,
      description: 'Verfahrensgebühr 1.3',
      issued_at: null,
    },
  ],
  reactions: [],
  bundle_prev_id: 2210,
  bundle_next_id: 2212,
  cases: [{ id: 'ADV-024-A', title: 'Weber ./. Weber', is_draft: false }],
  proceedings: [],
}

export const documentReader: Schemas['DocumentReader'] = {
  ...documentReview,
  case_id: 'ADV-024-A',
  case: { id: 'ADV-024-A', title: 'Hansen ./. Hansen', is_draft: false },
  body_html:
    '<p>Vorwort.</p><p>Der <mark id="p-p1" data-passage-id="p1" data-kind="disputed" class="hud-mark">Beklagte bestreitet</mark> alles.</p><p>Schluss mit Kosten.</p>',
  pins: [
    { id: 7, passage_id: 'p1', note: 'check this', user_id: 1, updated_at: '2026-10-06T08:00:00Z' },
  ],
  nav: {
    prev_doc_id: 2210,
    next_doc_id: 2212,
    position: 2,
    total: 5,
    parent_id: null,
    first_child_id: null,
    bundle_prev_id: null,
    bundle_next_id: null,
  },
  thread_open: true,
  context_strategy: null,
  has_original: true,
}

export const conversation: Schemas['ConversationDetail'] = {
  id: 31,
  scope_type: 'document',
  scope_id: '2211',
  title: null,
  messages: [],
}

export const caseDetail: Schemas['CaseDetail'] = {
  id: 'ADV-024-A',
  title: 'Vane ./. Vane',
  status: 'discovery',
  case_type: 'family',
  jurisdiction: 'de',
  is_draft: false,
  pending_close: false,
  close_suggestion_rationale: null,
  assume_worst_case: false,
  can_edit: true,
  can_manage_sharing: true,
  proceedings: [
    {
      id: 10,
      court_name: 'AG Hamburg',
      court_level: 'ag',
      az_court: '3 F 1/26',
      subject_matter: null,
      status: 'active',
      is_draft: false,
      doc_count: 2,
      is_deletable: false,
    },
    {
      id: 11,
      court_name: 'OLG Hamburg',
      court_level: 'olg',
      az_court: null,
      subject_matter: null,
      status: 'active',
      is_draft: false,
      doc_count: 0,
      is_deletable: true,
    },
  ],
  active_proceeding_id: 10,
  documents: [
    {
      id: 2211,
      title: 'Klageerwiderung.pdf',
      originator_type: 'opposing',
      document_type: null,
      issued_date: '2026-01-20T00:00:00Z',
      received_date: null,
      significance_tier: 'critical',
      role: 'standalone',
      thread_open: true,
      needs_review: false,
      is_new: true,
    },
    {
      id: 2210,
      title: 'Klageschrift.pdf',
      originator_type: 'own',
      document_type: null,
      issued_date: '2026-01-10T00:00:00Z',
      received_date: null,
      significance_tier: 'significant',
      role: 'standalone',
      thread_open: false,
      needs_review: false,
      is_new: false,
    },
  ],
  new_doc_count: 1,
  last_visit: null,
  action_items: [
    {
      id: 5,
      title: 'Erwiderung einreichen',
      description: null,
      due_date: '2026-10-20T00:00:00Z',
      action_type: 'deadline',
      status: 'open',
      location: null,
      addressee: null,
      proceeding_id: 10,
      source_document_id: 2211,
      is_overdue: false,
    },
  ],
  parties: [{ name: 'Vane', role: 'own', document_count: 1 }],
  opposing_parties: ['Müller'],
  brief: {
    status: 'ready',
    error: null,
    posture: 'Client seeks sole custody.',
    pressure_points: ['Welfare finding is contested.'],
    next_move: 'File the rebuttal.',
    detected_status: null,
    status_rationale: null,
    updated_at: '2026-10-01T00:00:00Z',
  },
  financials: {
    total_cost_exposure_cents: 1845000,
    booked: 119,
    paid: 0,
    outstanding: 119,
    reimbursable: 0,
  },
  open_claim_count: 3,
  dormancy_alert: null,
}

export const notificationsView: Schemas['NotificationsView'] = {
  total: 4,
  generated_at: '2026-06-17T06:40:00Z',
  groups: [
    {
      kind: 'overdue_deadline',
      count: 1,
      items: [
        {
          id: 11,
          kind: 'overdue_deadline',
          title: 'Stellungnahme Jugendamt',
          detail: null,
          amount: null,
          due_at: '2026-06-15T00:00:00Z',
          case_id: 'ADV-024-A',
          case_title: 'Weber ./. Weber',
          link: '/cases/ADV-024-A?view=review',
        },
      ],
    },
    { kind: 'upcoming_deadline', count: 0, items: [] },
    {
      kind: 'hearing',
      count: 1,
      items: [
        {
          id: 12,
          kind: 'hearing',
          title: 'Mündliche Verhandlung',
          detail: 'Saal 3',
          amount: null,
          due_at: '2026-07-02T09:00:00Z',
          case_id: 'ADV-024-A',
          case_title: 'Weber ./. Weber',
          link: '/cases/ADV-024-A?view=review',
        },
      ],
    },
    {
      kind: 'pending_triage',
      count: 1,
      items: [
        {
          id: 42,
          kind: 'pending_triage',
          title: 'Ladung AG Hamburg',
          detail: 'poststelle@ag-hamburg.de',
          amount: null,
          due_at: '2026-06-17T06:00:00Z',
          case_id: null,
          case_title: null,
          link: '/triage',
        },
      ],
    },
    {
      kind: 'overdue_cost',
      count: 1,
      items: [
        {
          id: 7,
          kind: 'overdue_cost',
          title: 'Gerichtskostenvorschuss',
          detail: null,
          amount: 1230,
          due_at: '2026-06-10T00:00:00Z',
          case_id: 'ADV-024-A',
          case_title: 'Weber ./. Weber',
          link: '/costs',
        },
      ],
    },
  ],
}

export const briefingView: Schemas['BriefingView'] = {
  status: 'ready',
  day: '2026-06-17',
  generated_at: '2026-06-17T06:40:00Z',
  model_label: 'qwen3.5:9b',
  external: false,
  summary: 'Two deadlines land this week.',
  priorities: ['ADV-024-A: file the counter-statement'],
  error: null,
}
